// DO NOT EDIT THIS FILE
/* File generated by:
	./vpp.pl \
	 -perl foo.vp -output foo.v
*/

    .D0(data[0]),
    .D1(data[1]),
    .D2(data[2]),
    .D3(data[3]),
    .D4(data[4]),
    .D5(data[5]),
    .D6(data[6]),
    .D7(data[7]),

// comment = 42
// 32 x 8 x 8 x 3
// Victory!
